version: '3'

services:
  db:
    image: postgres
    restart: always
    networks:
      - erp
    ports:
      - "${DB_PORT}:${DB_PORT}"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  service:
    build: .
    restart: always
    networks:
      - erp
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env.docker

networks:
  erp:
    name: erp
    driver: bridge
