# Generated by Django 5.0.6 on 2024-05-22 06:44

from django.db import migrations
from django.conf import settings
import os
import json


def add_users(apps, schema_editor):
    if settings.DEBUG:
        Employee = apps.get_model("employee_app", "Employee")

        app_dir = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))

        file_path = os.path.join(app_dir, "data/employeeData.json")

        with open(file_path, "r") as file:
            employee_data = json.load(file)

        for employee in employee_data:
            Employee.objects.create_user(
                username=employee["username"],
                password=employee["password"],
                name=employee["name"],
                role=employee["role"]
            )


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_users)
    ]
