# Generated by Django 5.0.6 on 2024-07-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0002_alter_employee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('SALES', 'Sales'), ('PROCUREMENT', 'Procurement'), ('HR', 'Human Resource')]),
        ),
    ]
