# Generated by Django 5.0.6 on 2024-07-24 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0003_alter_employee_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='plain_password',
            field=models.CharField(blank=True, null=True),
        ),
    ]
